name: Payload
main: com.jonahseguin.payload.Payload
version: ${project.version}
author: Jonah Seguin
website: jonahseguin.com
description: fail-safe asynchronous profile & object caching for spigot servers