name: Payload
main: com.jonahseguin.payload.Payload
version: 1.1.0
author: Jonah Seguin
website: https://jonahseguin.com
description: fail-safe asynchronous profile & object caching for spigot servers